name: Handle Release
on:
  release:
    types: [created]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Changelog
        id: fetch_changelog
        run: echo changelog=$(cat CHANGELOG.md) >> $GITHUB_OUTPUT
      - name: Process and Add Notes
        uses: blankochan/ShrimpleBuilder/format_release@master
        with:
          changelog: ${{steps.fetch_changelog.outputs.changelog}}
          token: ${{secrets.GITHUB_TOKEN}}

  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Build Release
        uses: blankochan/ShrimpleBuilder/build@master
        with:
          configuration: "Release"
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: .build/*.dll
